### ISSUE TITLE
My mistake, contribution of Sagittal accidentals

### ISSUE THREAD

**Issue by ianpotato** [euwbah/musescore-xen-tuner#9]
Dear euwbah,

thank you so much for this great plugin.
I have to admit I made a small mistake when looking at your sheet of accidentals. I must have dragged some other box onto the entry explaining layout offset, which deleted it... I'm sorry for that. To be honest I wasn't even aware I already had permission to edit the file.
As I'd really like to use a few Sagittal accidentals that aren't available yet, I figured I'd just contribute them (and the whole rest of them) myself. This is my first time working with GitHub, and even Spreadsheet, for that matter, so I'll try my best and submit it soon.
I might also be able to do some testing with Musescore 4.
I just wanted to contact you in advance because of my stupid mistake... I hope this is the right communication path for this.

Ian

**Comment by ianpotato** [comment]
So, I 've now realized that all the Sagittal accidentals are in fact available and I just didn't look corretcly.
I've made a simple Sagittal 311edo tuning (see attachment), you may of course include it if you'd like to. (Or I can make a pull request, I suppose this is how this works, right?)
[sagittal 311edo.txt](https://github.com/euwbah/musescore-xen-tuner/files/13252268/sagittal.311edo.txt)

**Comment by euwbah** [comment]
Really appreciate it! I didn't have time during the school term to fully understand Sagittal myself, so I was ready to do it this break (or procrastinate haha). Thanks for bringing the completion to 98%, really great work! Don't worry about the mistake, it's an easy fix.

Thanks for the Sagittal tuning config as well, would be very nice to have :)

Sorry I couldn't get back to you earlier as I'm quite busy and just doing this whenever I'm free.

Thanks again for the contributions!

**Comment by ianpotato** [comment]
No worries, I've been busy as well, I definitely understand. ;)

I really didn't contribute anything. I would have, but it had already been done. Whoever added all those accidentals deserves the credit. I thought some of them weren't there at first, but I had just made a mistake when searching the list.
